### ISSUE TITLE
Handle syllabification exceptions

### ISSUE THREAD

**Issue by versae** [linhd-postdata/rantanplan#44]
Use Ríos Mestre's massive resource: http://elies.rediris.es/elies4/Fon8.htm

An approximation is done in Navarro Colorado's ADSO: https://github.com/bncolorado/adsoScansionSystem/blob/master/analysis/resources/excepciones_silabeo.txt

**Comment by alvp** [comment]
Also investigate whether "ruido" has hyatus or not, Ríos Mestre says it's 'ru-i-do', but we should look for more modern references and maybe a RAE (or similiar) explanation-
